export const FETCH_PUBLICATION = "FETCH_PUBLICATION";
export const SUCCESS_PUBLICATION = "SUCCESS_PUBLICATION";
export const ERROR_PUBLICATION = "ERROR_PUBLICATION";

export const FETCH_PUBLICATION_BY_USER_ID = "FETCH_PUBLICATION_BY_USER_ID";
export const SUCCESS_PUBLICATION_BY_USER_ID = "SUCCESS_PUBLICATION_BY_USER_ID";
export const ERROR_PUBLICATION_BY_USER_ID = "ERROR_PUBLICATION_BY_USER_ID";
